n = input("Digite algo: ")
print("O tipo primitivo desse valor é", type(n))
print("Só tem espaço?", n.isspace())
print("É alfabético?", n.isalpha())
print("É alfanumérico?", n.isalnum())
print("É um número?", n.isnumeric())
print("Está em maiuscúla?", n.issupper())
print("Está em minuscúla?", n.islower())
print("Está capitalizada?", n.istitle())